//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameInstance
    {
        public int instanceID { get; set; }
        public int gameId { get; set; }
        public int playerId { get; set; }
        public int stars { get; set; }
        public int coins { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual player player { get; set; }
    }
}
